# Generated by Django 5.2.3 on 2025-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_body_notes_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
